name: Bug report
description: Report a defect in thynkai-toolkits.
labels: ["tooling", "bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
    validations:
      required: true

